<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.guoshisan</groupId>
    <artifactId>xiaohongshu-kv</artifactId>
    <version>0.0.1-SNAPSHOT</version>
  </parent>

  <!-- 打包方式 -->
  <packaging>jar</packaging>

  <artifactId>xiaohongshu-kv-api</artifactId>
  <name>${project.artifactId}</name>
  <description>RPC层, 供其他服务调用</description>

  <url>http://maven.apache.org</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
    <!-- OpenFeign -->
    <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter-openfeign</artifactId>
    </dependency>

    <!-- 负载均衡 -->
    <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter-loadbalancer</artifactId>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency><dependency><groupId>com.guoshisan</groupId><artifactId>shisan-common</artifactId></dependency>
  </dependencies>
</project>
